package com.chit.app.domain.session.application.dto

enum class SseEvent {
    STREAMER_SSE_INITIALIZATION,
    STREAMER_PARTICIPANT_ADDED,
    STREAMER_PARTICIPANT_REMOVED,
    STREAMER_SESSION_UPDATED,
    PARTICIPANT_ORDER_UPDATED,
}