spring:
  profiles:
    active: dev
    include:
      - oauth
      - jwt
      - api
      - log

  threads:
    virtual:
      enabled: true

  messages:
    encoding: UTF-8

  jpa:
    open-in-view: false
    properties:
      hibernate:
        javax:
          cache:
            uri: classpath:ehcache.xml
        jdbc:
          batch_size: 20
        order_updates: true
        cache:
          use_second_level_cache: true
          region.factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory

  flyway:
    enabled: false

  datasource:
    hikari:
      maximum-pool-size: 25
      leak-detection-threshold: 5000

springdoc:
  swagger-ui:
    path: /swagger-ui.html