spring:
  profiles:
    active: dev
    include:
      - oauth
      - jwt
      - api

  threads:
    virtual:
      enabled: true

  messages:
    encoding: UTF-8

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_updates: true
        cache:
          use_second_level_cache: true
          region.factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory

  flyway:
    enabled: false

  cache:
    jcache:
      config: classpath:ehcache.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html